import type { PublicationInput } from "../schemas/publication";

/**
 * Dados de exemplo do catálogo.
 *
 * São volumes reais da Panini DC. Os seis primeiros vieram de uma execução do
 * importador contra o site (SKU, formato, páginas e "Conteúdo original"
 * conferidos); os demais foram preenchidos à mão no mesmo formato.
 *
 * Isto é semente de desenvolvimento, não fonte de verdade — quando o importador
 * entrar em operação ele sobrescreve estes registros pelo mesmo `sku`.
 *
 * `coverImage` aponta para o CloudFront da Panini: referenciamos a URL de
 * origem, nunca copiamos o arquivo.
 */

const COVER_BASE = "https://d14d9vp3wdof84.cloudfront.net/image";

export const SEED_PUBLICATIONS: PublicationInput[] = [
  {
    slug: "superman-por-geoff-johns-vol-04",
    sku: "ASMGJ004",
    title: "Superman Por Geoff Johns Vol. 04",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Superman por Geoff Johns",
    volumeNumber: 4,
    format: "hardcover",
    pages: 120,
    priceBRL: 72.9,
    ageRating: "12 anos",
    releasedAt: new Date("2026-11-01T00:00:00Z"),
    coverImage: `${COVER_BASE}/589816272436/image_uc8bqe9oo11pv6opcu23i6bp0c/-S800-FWEBP`,
    originalContents: [
      {
        raw: "Action Comics (1938) 855-857",
        series: "Action Comics",
        volumeYear: 1938,
        issues: [855, 856, 857],
      },
      {
        raw: "Action Comics Annual (1987) 10",
        series: "Action Comics",
        qualifier: "Annual",
        volumeYear: 1987,
        issues: [10],
      },
    ],
    creators: [{ name: "Geoff Johns" }, { name: "Richard Donner" }, { name: "Eric Powell" }],
    characters: ["Superman", "Bizarro"],
    reviewStatus: "approved",
  },
  {
    slug: "dc-de-ouro-mulher-maravilha",
    sku: "AMOUR001",
    title: "DC De Ouro: Mulher-Maravilha",
    publisher: "Panini",
    universe: "DC Comics",
    line: "DC de Ouro",
    format: "hardcover",
    pages: 392,
    priceBRL: 189.9,
    ageRating: "12 anos",
    releasedAt: new Date("2026-08-01T00:00:00Z"),
    originalContents: [
      {
        raw: "All Star Comics (1940) 8",
        series: "All Star Comics",
        volumeYear: 1940,
        issues: [8],
      },
      {
        raw: "Sensational Comics (1942) 1-14",
        series: "Sensational Comics",
        volumeYear: 1942,
        issues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
      },
      {
        raw: "Wonder Woman (1942) 1-3",
        series: "Wonder Woman",
        volumeYear: 1942,
        issues: [1, 2, 3],
      },
      {
        raw: "Comics Cavalcade (1942) 1",
        series: "Comics Cavalcade",
        volumeYear: 1942,
        issues: [1],
      },
    ],
    creators: [{ name: "William Moulton Marston" }, { name: "Harry G. Peter" }],
    characters: ["Mulher-Maravilha"],
    reviewStatus: "approved",
  },
  {
    slug: "batman-padroes-sombrios-vol-02",
    sku: "APSOM002",
    title: "Batman: Padrões Sombrios Vol. 02",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Batman: Padrões Sombrios",
    volumeNumber: 2,
    format: "periodical",
    pages: 152,
    priceBRL: 54.9,
    ageRating: "16 anos",
    releasedAt: new Date("2026-10-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Batman: Dark Patterns 7-12",
        series: "Batman: Dark Patterns",
        issues: [7, 8, 9, 10, 11, 12],
      },
    ],
    creators: [{ name: "Dan Watters" }, { name: "Hayden Sherman" }],
    characters: ["Batman"],
    reviewStatus: "approved",
  },
  {
    slug: "dc-ko-especial-combate-01",
    sku: "AROCO001",
    title: "DC K.O. Especial: Combate 01",
    publisher: "Panini",
    universe: "DC Comics",
    line: "DC K.O.",
    volumeNumber: 1,
    format: "periodical",
    pages: 136,
    priceBRL: 49.9,
    ageRating: "14 anos",
    releasedAt: new Date("2026-09-01T00:00:00Z"),
    originalContents: [
      {
        raw: "DC K.O.: Superman vs Captain Atom (2025) 1",
        series: "DC K.O.: Superman vs Captain Atom",
        volumeYear: 2025,
        issues: [1],
      },
      {
        raw: "DC K.O.: Wonder Woman vs Lobo (2025) 1",
        series: "DC K.O.: Wonder Woman vs Lobo",
        volumeYear: 2025,
        issues: [1],
      },
      {
        raw: "DC K.O.: Harley Quinn vs Zatanna (2025) 1",
        series: "DC K.O.: Harley Quinn vs Zatanna",
        volumeYear: 2025,
        issues: [1],
      },
      {
        raw: "DC K.O.: The Joker vs Red Hood (2025) 1",
        series: "DC K.O.: The Joker vs Red Hood",
        volumeYear: 2025,
        issues: [1],
      },
    ],
    creators: [{ name: "Scott Snyder" }],
    characters: ["Superman", "Mulher-Maravilha", "Arlequina", "Coringa"],
    reviewStatus: "approved",
  },
  {
    slug: "jovens-titas-em-acao-15",
    sku: "ATTGO015",
    title: "Jovens Titãs Em Ação 15",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Teen Titans Go!",
    volumeNumber: 15,
    format: "periodical",
    pages: 48,
    priceBRL: 19.9,
    ageRating: "Livre",
    releasedAt: new Date("2026-09-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Teen Titans Go! (2013) 29-30",
        series: "Teen Titans Go!",
        volumeYear: 2013,
        issues: [29, 30],
      },
    ],
    creators: [{ name: "Sholly Fisch" }],
    characters: ["Robin", "Ravena", "Estelar", "Mutano", "Ciborgue"],
    reviewStatus: "approved",
  },
  {
    slug: "vingadores-lja-03",
    sku: "ALJVI003V",
    title: "Vingadores/LJA 03",
    publisher: "Panini",
    universe: "DC Comics",
    line: "LJA/Vingadores",
    volumeNumber: 3,
    format: "periodical",
    pages: 48,
    priceBRL: 24.9,
    ageRating: "12 anos",
    releasedAt: new Date("2026-07-01T00:00:00Z"),
    originalContents: [{ raw: "JLA/Avengers 3", series: "JLA/Avengers", issues: [3] }],
    creators: [{ name: "Kurt Busiek" }, { name: "George Pérez" }],
    characters: ["Superman", "Batman", "Capitão América", "Homem de Ferro"],
    reviewStatus: "approved",
  },
  {
    slug: "batman-ano-um",
    sku: "SEED-BAU001",
    title: "Batman: Ano Um",
    publisher: "Panini",
    universe: "DC Comics",
    line: "DC Icons",
    format: "hardcover",
    pages: 144,
    priceBRL: 89.9,
    ageRating: "16 anos",
    releasedAt: new Date("2025-03-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Batman (1940) 404-407",
        series: "Batman",
        volumeYear: 1940,
        issues: [404, 405, 406, 407],
      },
    ],
    creators: [{ name: "Frank Miller" }, { name: "David Mazzucchelli" }],
    characters: ["Batman", "James Gordon", "Selina Kyle"],
    reviewStatus: "approved",
  },
  {
    slug: "watchmen",
    sku: "SEED-WTC001",
    title: "Watchmen",
    publisher: "Panini",
    universe: "DC Comics",
    line: "DC Deluxe",
    format: "hardcover",
    pages: 416,
    priceBRL: 199.9,
    ageRating: "18 anos",
    releasedAt: new Date("2025-06-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Watchmen (1986) 1-12",
        series: "Watchmen",
        volumeYear: 1986,
        issues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      },
    ],
    creators: [{ name: "Alan Moore" }, { name: "Dave Gibbons" }, { name: "John Higgins" }],
    characters: ["Rorschach", "Dr. Manhattan", "Coruja"],
    reviewStatus: "approved",
  },
  {
    slug: "a-piada-mortal",
    sku: "SEED-APM001",
    title: "Batman: A Piada Mortal",
    publisher: "Panini",
    universe: "DC Comics",
    line: "DC Deluxe",
    format: "hardcover",
    pages: 64,
    priceBRL: 64.9,
    ageRating: "16 anos",
    releasedAt: new Date("2025-04-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Batman: The Killing Joke (1988) 1",
        series: "Batman: The Killing Joke",
        volumeYear: 1988,
        issues: [1],
      },
    ],
    creators: [{ name: "Alan Moore" }, { name: "Brian Bolland" }],
    characters: ["Batman", "Coringa", "Barbara Gordon"],
    reviewStatus: "approved",
  },
  {
    slug: "lanterna-verde-vol-01",
    sku: "SEED-LNV001",
    title: "Lanterna Verde Vol. 01",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Lendas do Universo DC",
    volumeNumber: 1,
    format: "paperback",
    pages: 176,
    priceBRL: 44.9,
    ageRating: "12 anos",
    releasedAt: new Date("2025-09-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Green Lantern (2005) 1-6",
        series: "Green Lantern",
        volumeYear: 2005,
        issues: [1, 2, 3, 4, 5, 6],
      },
    ],
    creators: [{ name: "Geoff Johns" }, { name: "Carlos Pacheco" }],
    characters: ["Lanterna Verde", "Hal Jordan"],
    reviewStatus: "approved",
  },
  {
    slug: "sandman-vol-01",
    sku: "SEED-SND001",
    title: "Sandman Vol. 01: Prelúdios e Noturnos",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Vertigo Deluxe",
    volumeNumber: 1,
    format: "hardcover",
    pages: 240,
    priceBRL: 149.9,
    ageRating: "18 anos",
    releasedAt: new Date("2026-02-01T00:00:00Z"),
    originalContents: [
      {
        raw: "The Sandman (1989) 1-8",
        series: "The Sandman",
        volumeYear: 1989,
        issues: [1, 2, 3, 4, 5, 6, 7, 8],
      },
    ],
    creators: [{ name: "Neil Gaiman" }, { name: "Sam Kieth" }, { name: "Mike Dringenberg" }],
    characters: ["Morpheus", "Morte"],
    reviewStatus: "approved",
  },
  {
    slug: "liga-da-justica-origem",
    sku: "SEED-LJO001",
    title: "Liga da Justiça: Origem",
    publisher: "Panini",
    universe: "DC Comics",
    line: "Novos 52",
    format: "paperback",
    pages: 192,
    priceBRL: 54.9,
    ageRating: "12 anos",
    releasedAt: new Date("2025-11-01T00:00:00Z"),
    originalContents: [
      {
        raw: "Justice League (2011) 1-6",
        series: "Justice League",
        volumeYear: 2011,
        issues: [1, 2, 3, 4, 5, 6],
      },
    ],
    creators: [{ name: "Geoff Johns" }, { name: "Jim Lee" }, { name: "Scott Williams" }],
    characters: ["Batman", "Superman", "Mulher-Maravilha", "Flash", "Ciborgue"],
    reviewStatus: "approved",
  },
];
